name: "DEV DEPLOY"


on:
  push:
		branches:
			- develop
		   
permissions:
	id-token: write
	contents: read

jobs:
	terraform:
		uses: ./.github/workflows/terraform.yml
		with:
			enviroment: dev
			aws-assume-role-arn: "arn:aws:iam::183631349055:role/github-actions-caiohmb-pipeline"
			aws-region: "us-east-1"
			aws-statefile-s3-bucket: "caiohmb-us-east-1-terraform-statefile"
			aws-lock-dynamodb: "caiohmb-us-east-1-terraform-lock"